### ISSUE TITLE
An attempt to crack this

### ISSUE THREAD

**Issue by ethanresnick** [photomattmills/penumbra-code#1]
Hey Matt,

I like your idea of hiding frequency by varying the number of ciphertext characters associated with each plaintext character, but I think the key would still be deducible pretty easily by looking at digraphs.

The idea is to take advantage of the fact that the frequency at which a digraph occurs is different from simply the average of the frequencies at which its component letters occur. E.g. r and l are both fairly common, but "rl" rarely, if ever, appears.

Here's a more detailed algorithm for how I could see it working, assuming its understood that the text was encrypted with your suggestions for hiding frequency:
1. The computer counts the number of unique glyphs in the ciphertext and, knowing the frequency of each letter in the underlying language, can reverse engineer how many glyphs are dedicated to subbing in for each character.
2. Then the computer can figure out how many ways a given digraph can be represented (e.g. if there are 7 glyphs for "f" and 30 for "a", there'd be 7*30 ways to represent "fa"). 
3. By diving the relative frequency of every digraph in the language frequency by the number of ways to get that digraph, the computer could build a table of which sets of digraphs are likely to occur more often than others. E.g. it would know that each of the 7*30 representations of "fa" is likely to occur at some frequency throughout the text, and that that's greater than the frequency at which each representation of "fg" is likely to occur, because even though there are more potential representations of "fa", there aren't so many more that it can overpower a digraph like "fg" that rarely occurs.
4. From there it's pretty simple. You guess and check and possibly change the initial parameters (e.g. how many characters you said each plaintext char was mapped to) slightly to account for any minor differences between the texts you built your frequency estimates from and the plaintext that's been encrypted.

Thoughts?

**Comment by photomattmills** [comment]
I think this would work, assuming you knew the cryptosystem in use, to get the key out; however, doing regular digraph analysis on what looks like random plaintext with no knowledge of the cypher wouldn't get you much. (Feel free to prove me wrong with actual analysis of a cyphertext). The rules of this game are that you have to break the code with no knowledge of the cypher, other than what can be derived from the cyphertext.

**Comment by photomattmills** [comment]
Also, under 'todo': if you're willing to forego some complexity in the number of characters, or if you have an especially large number of glyphs, you could have some characters represent nothing, and salt them randomly throughout.

**Comment by robinsloan** [comment]
I love that you guys are thinking about this.

Maybe this is implicit in what you've been saying, Ethan, and I'm missing it, but just in case: I think the key here is that your cyphertext has been downsampled, & therefore you've actually lost some data. Possibly a significant amount.

For example, If I use a super-dumb system to encode SLOAN and write it down like this…

TMPBO

…but then you transcribe it like this…

TTBBO

…because, for whatever reason, you can't recognize the differences between many of the original characters—it's going to be tough for you to decode that, right?

That's precisely what's happening when, in the story, everybody—the Unbroken Spine and Google alike—are transcribing…

[Swoopy capital S] [alternate L number 3] [standard O] [A-N ligature]

…into…

SLOAN

So it's actually not the complexity of the code that's been holding people back—it's the unwitting downsampling of the cyphertext, and the accompanying data loss.

Now: whether that would actually be sufficient to stymie them for 500 years, I don't know.

**Comment by ethanresnick** [comment]
@robinsloan Ahh...I understand what you meant now about downsampling, and I think you're right: if the cyphertext is being misread, then there's no way it's going to be decoded. And this kind of thing would definitely stump OCR/Google. Don't think @mattmills or I originally got that that's what was happening.

@mattmills Given Robin's last comment, I guess the above thread is irrelevant. I will say though that I think it's fair game here to assume the cipher could have been guessed (if only by trial and error), such that "could it be broken given knowledge of the cipher" is a fair standard.
